server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springingDemo
    username: postgres
    password: secret

  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create
